FROM python:3.8-slim-buster

RUN apt-get update -q \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    libgl1-mesa-dev \
    libgl1-mesa-glx \
    libglew-dev \
    libosmesa6-dev \
    software-properties-common \
    patchelf

RUN apt-get install -y --no-install-recommends -o APT::Immediate-Configure=false gcc g++ git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


ENV PYTHONUNBUFFERED 1
ADD ./agent /
ADD ./utils /
ADD requirements/agent.txt /
RUN pip install --upgrade pip
RUN pip install -r agent.txt -f https://download.pytorch.org/whl/torch_stable.html
ADD ./MyoSuite-1.1.0-py2.py3-none-any.whl /
RUN pip install MyoSuite-1.1.0-py2.py3-none-any.whl
CMD [ "python", "agent_die_rotate.py" ]
