name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Set EvalAI token
      run: |
        echo ${{ secrets.AUTH_TOKEN }}
        evalai set_token ${{ secrets.AUTH_TOKEN }}
        
        
    - name: Register the token to identify your contribution
      run: pip install "evalai>=1.3.13"
      
    - name: Test that the registration was successful. MyoChallenge needs to be in the list returned
      run: evalai challenges --participant
    
    - name: Build the Docker image
      run: docker build -f docker/agent/Dockerfile_DieEnv . -t myochallengeeval_die_agent
