name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install evalAI
      run: pip install "evalai>=1.3.13"

    - name: Set EvalAI token
      run: |
        echo "The GitHub Action Secret will be masked:  "
        echo ${{ secrets.EvalAI_token }}
        echo "Trick to echo GitHub Actions Secret:  "
        echo ${{secrets.EvalAI_token}} | sed 's/./& /g' 

        evalai set_token ${{ secrets.EvalAI_token }}
            
    - name: Test that the registration was successful. MyoChallenge needs to be in the list returned
      run: evalai challenges --participant
    
    - name: Build the Docker image
      run: docker build -f docker/agent/Dockerfile_DieEnv . -t myochallengeeval_die_agent
